# ./docker-compose.yml
services:
  nginx:
    image: nginx:latest # Utiliza la última imagen oficial de Nginx
    container_name: ar-nginx-ssl
    ports:
      - "80:80"   # Puerto HTTP
      - "443:443" # Puerto HTTPS
    volumes:
      # Monta tu archivo de configuración de Nginx personalizado
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Monta el directorio de certificados SSL dentro del contenedor
      - ./nginx/certs:/etc/nginx/certs:ro
      # Monta tu carpeta de proyectos de la aplicación
      # La estructura dentro del contenedor será /var/www/html/default-project/index.html
      - ./app:/var/www/html:ro # 'ro' significa sólo lectura
    restart: always # Siempre reinicia el contenedor si se detiene